{% set version = "1.2.3.0" %}

package:
    name: mintpy_test4
    version: {{ version }}

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - scons
        - cython
    host:
        - python
        - gdal
        - fftw
        - cython
    run:
        - python
        - gdal
        - libgdal
        - numpy
        - scipy
        - fftw
        - cartopy
        - cdsapi
        - cvxopt
        - dask
        - dask-jobqueue
        - defusedxml
        - ecCodes
        - gfortran_linux-64
        - gfortran_osx-64
        - h5py
        - lxml
        - matplotlib
        - netcdf4
        - numpy
        - openmp
        - pygrib
        - pyhdf
        - pykdtree
        - pyproj
        - pyresample
        - setuptools
        - scikit-image
        - scikit-learn
        - scipy
about:
    home: https://github.com/mehdizadehm/MintPy
    summary: Mintpy Beta Version
    dev_url: https://github.com/mehdizadehm/MintPy

source:
      url: https://github.com/mehdizadehm/MintPy/archive/v{{ version }}.tar.gz
      folder: mintpy_beta
      sha256: b8e44095658de12f4778c38d4ed47ea0da23bd2d61138f06be1cadcd0d866143

