{% set version = "1.2.3.01" %}

package:
    name: mintpy_test4
    version: {{ version }}


requirements:
      build:
          - {{ compiler('c') }}
      host:
          - python
          - pip
      run:
          - python
          - gdal
          - libgdal
          - numpy
          - scipy
          - fftw

about:
    home: https://github.com/mehdizadehm/MintPy
    summary: Mintpy Beta Version
    dev_url: https://github.com/mehdizadehm/MintPy

source:
      url: https://github.com/mehdizadehm/MintPy/archive/v{{ version }}.tar.gz
      folder: mintpy_beta
      sha256: 4799e31c14aa931839c2a70b2fdfebfef47be2d4ac48e9ba5a207da06a2df090
